### ISSUE TITLE
Not colorblind friendly

### ISSUE THREAD

**Issue by RobotCaleb** [Monofraps/clang-format.me#1]
I have a common form of color blindness. The red/green for the options toggles is pretty painful. I hate guess if white to the left means on or color to the left means on.

Symbols are always preferred over colors. Rule of thumb is don't rely on color alone to convey information.

Rare, but also possible, is the person that can not see any colors at all. Not sure how well red/green translates to an eye's gray scale.

**Comment by nristock** [comment]
Hi, thank you for pointing that out. I'll probably put some text on it or create a color blind mode when I have some time.

**Comment by RobotCaleb** [comment]
Very cool. Thanks!

(side note, is this supposed to be available at http://clang-format.me? I
can only seem to hit it at http://cf.monofraps.net/)

**Comment by nristock** [comment]
Oh yeah, the website will definitely be available on clang-format.me soon
... Guess I just never got around to setting that up, yet.
